# One-paragraph descriptions for every parameter, keyed by parameter ID.
# generate.py checks that every ID in engine/src/Params.cpp has an entry here.

DOCS = {
    # timing
    "sync_mode": "**Tempo**: trace length follows the host's tempo and traces line up with its bar grid. **Free**: trace length is set in milliseconds and runs from when playback starts.",
    "trace_ms": "Trace length when Sync is Free: 10 ms (grains) to 20 s.",
    "trace_division": "Trace length when Sync is Tempo: 1/16 note to 4 bars. The default is 1 bar.",
    # memory
    "capacity": "The most traces memory holds (1–4000). Changing it keeps the traces that fit: clamped ones first, then the newest.",
    "memory_budget": "Audio memory reserved for traces (128 MB – 4 GB). With many traces the budget limits the longest trace a slot can hold; the status bar shows that limit (*slot max*).",
    "full_policy": "Which trace makes room when memory is full: **Oldest** (tape-like), **Random**, **Least Used** (lowest recent activation), **Weakest** (most faded), **Merge Similar** (average the new trace into its closest unclamped one) or **Reject** (keep what's there). Clamped traces are never replaced.",
    "merge_threshold": "Merge a new trace into an existing one whenever they are at least this similar, even if there is room. Prototypes form. 1 = off.",
    "freeze": "Stop storing and stop forgetting. Memory keeps answering, like the Space Echo's infinite repeat.",
    # writing
    "write_mode": "**Auto** stores every trace that passes the gates. **Manual** stores only captured traces.",
    "capture": "A rising edge stores the trace in progress, bypassing the gates and freeze. Same as the Capture button.",
    "write_gate_db": "Traces quieter than this aren't stored. −100 dB = off.",
    "novelty_mode": "**Store Novel**: store a trace only if nothing in memory is this similar. **Store Familiar**: only if something is. **Off**: no novelty test.",
    "novelty_threshold": "The similarity used by the Novelty Gate.",
    "write_probability": "The chance that a trace is stored.",
    "record_source": "What gets stored: the **Input** (plus feedback), the **Echo** (memory feeds on its own output and keeps sustaining after the input stops), or both.",
    # clamping
    "clamp_incoming": "Clamp every newly stored trace (within the clamp budget).",
    "clamp_budget": "The largest fraction of memory that may be clamped, so memory can still change.",
    "clamp_protects": "Clamped traces are exempt from forgetting (fading and feature loss).",
    "trigger_clamp_last": "Switching it on clamps the newest trace. For MIDI mapping and automation.",
    "trigger_clamp_all": "Switching it on clamps the newest traces up to the clamp budget.",
    "trigger_unclamp_all": "Switching it on unclamps every trace.",
    "trigger_clear_unclamped": "Switching it on forgets every unclamped trace.",
    "trigger_clear_all": "Switching it on clears memory.",
    # forgetting
    "encoding_failure": "MINERVA's *L*: the probability that each feature of a stored trace's address is lost at encoding. The heard cue stays intact.",
    "content_dropout": "At recording, each 1/32 of a trace may drop out (a tape dropout).",
    "decay_forget": "Each segment, every unclamped trace loses each of its features with this probability: recall gets vaguer.",
    "decay_fade_db": "Each segment, every unclamped trace loses this much strength (activation). Traces below −60 dB are forgotten.",
    "wear_tone": "Older traces play back duller, like worn tape.",
    # cueing
    "cue_mode": "**Segment**: each finished segment cues memory for the next (a delay-like echo). **Progressive**: memory is re-cued as each segment unfolds. **Rolling**: no grid; the last *Rolling Window* of input is searched for inside every trace.",
    "progressive_start": "The slot (of 16 per segment) from which the progressive cue takes over.",
    "rolling_window_ms": "Rolling: the length of the live cue.",
    "rolling_interval_ms": "Rolling: how often memory is searched.",
    "lookahead_ms": "Prediction: play memory this far ahead of the current position, so you hear what came next last time.",
    "cue_smoothing_ms": "Crossfade whenever a live cue (Progressive or Rolling) changes the echo.",
    "cue_source": "What cues memory: the **Input**, the **Sidechain** (another track routed to the plug-in's sidechain input), a **Random** address (memory dreams), **Frozen** (the last live cue, held), or **Echo Chain** (each echo cues the next; see [Sequences](../guide/sequences.qmd)).",
    "feature_focus": "Compare **Full** addresses, **Rhythm** only (loudness over time) or **Timbre** only (average spectrum). Segment and Progressive cueing.",
    "recency": "Favour recently stored traces (0 = no preference).",
    # sequential context
    "sequence_context": "Every trace also stores the previous segment's address, [n−1 | n]. On: cues use that context (Context Cue). Context is recorded either way, so you can switch it on later.",
    "context_cue": "**Match Both**: the last two segments against [n−1 | n] (sequence-sensitive recall). **Predict Next**: the last segment against traces' n−1 halves, so you hear what came next last time. **Current Only**: ordinary MINERVA II.",
    "context_weight": "Match Both: how much the n−1 half counts (0 = like Current Only, 1 = as much as the current half).",
    "chain_input": "Echo Chain: how much the live input steers the chain. 0 = memory walks on its own; 1 = the same as Predict Next from the input.",
    "chain_step": "Echo Chain: what cues the next step. **Sample**: one of the answering traces, drawn in proportion to its activation (a random walk through memory; with Playback = Sample it is the trace you hear). **Blend**: the echo's blended content (deterministic; tends to settle on a prototype).",
    "cue_noise": "Random noise (in standard deviations of the address) added to every cue: live, chain, iterative and progressive. Knocks retrieval out of ruts; also *fuzzy hearing* for live cues.",
    "habituation": "Traces that just answered are less active for a few segments (their fatigue halves each segment), so memory moves on instead of repeating itself.",
    # heads
    "mode_selector": "The RE-201's head combinations: 1, 2, 3, 2+3, 1+2, 1+3, 1+2+3 (delay heads), Iterative 1+2+3, or **Custom** (use the per-head settings below).",
    "head1_level_db": "Level of head 1, the main echo.",
    "head1_pan": "Pan of head 1.",
    "head2_mode": "Custom mode only. **Delay**: replays what head 1 played one segment earlier. **Iterative**: cued by head 1's echo (the echo of the echo).",
    "head2_level_db": "Level of head 2.",
    "head2_pan": "Pan of head 2.",
    "head3_mode": "Custom mode only. **Delay**: replays what head 1 played two segments earlier. **Iterative**: cued by head 2's echo.",
    "head3_level_db": "Level of head 3.",
    "head3_pan": "Pan of head 3.",
    # playback
    "playback": "**Blend**: every active memory, weighted (MINERVA's echo). **Voices**: the strongest few as separate chorus voices. **Sample**: one memory at a time, drawn at random by activation.",
    "voices": "Voices: how many memories play.",
    "voice_spread": "Voices: how far they fan out across the stereo field (the strongest stays in the centre).",
    "voice_detune": "Voices: detuning of the outermost voices.",
    "voice_delay_ms": "Voices: delay of the outermost voices.",
    "echo_tone_hz": "A low-pass on the echo. 20 kHz = off.",
    "intensity_to_tone": "Familiarity (the strongest activation) moves the echo tone: familiar echoes brighter (+) or darker (−).",
    "intensity_to_feedback": "Familiarity changes the feedback: familiar echoes feed back more (+) or less (−).",
    # retrieval
    "power": "The activation exponent. 1 = every memory contributes (a blurred *schema*); 9 = only the closest memories answer.",
    "similarity": "**Hintzman** (MINERVA II's normalised dot product) or **Cosine**.",
    "feature_mode": "**Continuous** feature values, or classic MINERVA −1/0/+1 (**Ternary**).",
    "ternary_threshold": "Ternary: how far (in standard deviations) a feature must be from the trace's average to count as +1 or −1.",
    "self_match": "On: the segment just played can answer its own cue (the delay-like part). Off: memory answers only with *earlier* traces.",
    "cue_gate_db": "Segments quieter than this don't cue memory, so the noise floor doesn't trigger echoes.",
    "negative_mode": "What negative activations do: **Subtract** (phase-inverted, true MINERVA), **Ignore**, or **Absolute**.",
    "normalization": "**Sum** (constant loudness), **Max**, or **Familiarity** (the echo is quiet when the cue resembles nothing in memory).",
    "level_tracking": "1: the echo's level follows the cue's, like a tape repeat, so feedback decays. 0: memories return at their own level.",
    # tape
    "length_mismatch": "A trace recorded at another trace length (you changed the repeat rate or the tempo): **Varispeed** plays it faster or slower to fit (pitch follows, like tape), **Cut** plays it as recorded, **Loop** repeats a shorter trace, **Stretch** time-stretches it to fit and keeps its pitch.",
    "wow": "Slow, drifting speed wobble (~0.5 Hz, up to 6 ms).",
    "flutter": "Fast speed wobble (~7 Hz, up to 0.5 ms).",
    "tape_drive": "Soft saturation of the echo (unity for quiet signals); also shapes what feeds back.",
    "hiss_db": "Tape noise on the echo. −100 dB = off. With feedback it gets recorded too.",
    "feedback_bass_db": "Low shelf (250 Hz) inside the feedback path: each repeat gets fuller or thinner.",
    "feedback_treble_db": "High shelf (3 kHz) inside the feedback path: each repeat gets brighter or darker.",
    "spring_level_db": "Spring reverb on the echo. −60 dB = off.",
    "spring_decay": "Spring reverb decay time.",
    "spring_on_dry": "The spring also gets the dry signal, as in the RE-201's reverb modes.",
    # spectral
    "blend_domain": "**Waveform**: the echo sums trace audio (exact, but unaligned memories can cancel). **Spectral**: magnitudes are summed and each frequency takes the phase of the memory loudest there, so memories blend without cancelling.",
    "spectral_voices": "Spectral: how many of the most active memories are analysed each frame (1–32).",
    "spectral_freeze": "Hold the echo's spectrum as a drone. Memory can change or be cleared underneath it.",
    "max_active": "A blend uses at most this many of the most active traces (the level is kept). Keeps huge memories cheap.",
    # output
    "feedback": "Echo mixed back into what gets recorded (soft-clipped; above 1 is allowed).",
    "echo_level_db": "Echo level. −60 dB = off.",
    "dry_level_db": "Dry level. −60 dB = off.",
    "edge_fade_ms": "Fade length at trace edges and when the echo changes (declicking).",
    "output_gain_db": "Output gain.",
    # running
    "running": "**Paused**: memory is left exactly as it is (nothing stored, forgotten or cued), the echo fades out and the dry signal passes. Resuming starts cleanly at the next segment. Not changed by presets.",
    # plugin
    "embed_memory": "Save memory inside the Live set (off by default: about 23 MB per minute of stored audio).",
    "midi_control": "MIDI notes trigger actions (see [MIDI and automation](../guide/midi.qmd)).",
    "midi_channel": "The channel MIDI notes are read on (0 = any).",
    "midi_base_note": "The first note of the MIDI map (default 36, C1 in Live).",
}
